##################################################
# DO Community Playbooks: LEMP on Ubuntu 18.04
##################################################
---
- hosts: Ub1
  become: true
  vars_files:
    - vars/default.yml

  tasks:
    - name: Install PHP Packages
      apt: name={{ item }} update_cache=yes state=latest
      loop: ['php-fpm', 'php-mysql', 'php-cli', 'php-curl', 'php-gd', 'php-mbstring', 'php-xml', 'php-zip']
    

# Sets Up PHP Info Page
    - name: Creates directory
      file:
        path: /var/www/html/mysute
        state: directory
    
    
    - name: Copy config
      template:
        src: "template/config.j2"
        dest: "/var/www/html/mysute/config.php"

    - name: Copy index
      template:
        src: "template/index.j2"
        dest: "/var/www/html/mysute/index.php"
